spring:
  application:
    name: 2025UthonServer
  sql:
    init:
      mode: embedded
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PW}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080

jwt:
  secret-key: ${JWT_SECRET}
  access-token-expiration: 172800000
  refresh-token-expiration: 604800000

cloud:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET}
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: ${AWS_S3_ACCESS_KEY_ID}
      secretKey: ${AWS_S3_SECRET_ACCESS_KEY}