spring:
  application:
    name: 2025UthonServer
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PW}
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379
server:
  port: 8080

jwt:
  secret-key: ${JWT_SECRET}
  access-token-expiration: 172800000
  refresh-token-expiration: 604800000

